# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1de434b1190b58cea2bd6d7d86bbb760ce85dcda7664b8536ab88c3489f9f8efc28f9cfdd6d033dd552ec85ac662a5d2cf7c3d3a99744a8dae4505b18019fe58

test:
  secret_key_base: d00c7b241dc4471daad004e50ebe3d7daf4494587adca354af50a30daa0fcd2a7a3647d77a1cfd34dda66988a5c8e67c00713ab3fe3ecb2c303c74a29df006b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
